### ISSUE TITLE
Trustpilot error on Product Page

### ISSUE THREAD

**Issue by odera89** [takeshape/penny#141]
After i installed the project to my localhost and setup according your Readme, the product page is no longer to work.

![Screenshot 2022-12-16 at 14 41 31](https://user-images.githubusercontent.com/1921763/208100544-5cd84771-cdc4-446d-9b79-00d80de65ae3.png)

After I delete these lines from src/features/ProductPage/queries.takeshape.ts
![Screenshot 2022-12-16 at 14 45 00](https://user-images.githubusercontent.com/1921763/208101067-8b5fae1d-f66e-4be9-a679-88402efd7613.png) started to work.

Notice that the enableTrustpilot variables src/config/reviews.ts is false.

I mess something from the install? or is a bug?

Thank you,
Hunor

**Comment by asprouse** [comment]
Hi @odera89! This is a bug and we have a workaround in this PR #142. We are developing a better long term solution for customizing your project

**Comment by mshick** [comment]
Hi @odera89 , hopefully the merged PR @asprouse linked helped out? Feel free to re-open this issue if you're still having issues getting rid of the Trustpilot errors.
